### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Idlusen** [usineur/go-neufbox#1]
Could you give some directions about the building process in the readme?

**Comment by Idlusen** [comment]
Are a specific go environment and libraries assumed to be installed for building? It seems it’s got quite some dependencies.

**Comment by usineur** [comment]
hi, sorry for my late answer, i seemed that i deactivated the noficitions.

To build it, you need to specify a GOPATH like this: export GOPATH=/home/${user}/.go

Then, you just need to execute: go get github.com/usineur/go-neufbox

Deps are the followings: libxml2-devel, libcurl-devel

**Comment by Idlusen** [comment]
Well better late than never, I’ll give it a try, thank you!
